language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t spark .
  - docker run --entrypoint /bin/bash --name spark spark -c "pip list"

script:
  - docker ps -a

notifications:
  slack:
    secure: BbmkuSyK7yUeo2aQOjxHzfiT0owkswOri4Mil2oBUMobOKIGOx/mtd11+h9KPPDXF8Ziw0S0wHEuWIHWHMiKAvU4aPiSDkgIbjX5NcqiMWRZxKSzes8wTa4ngXIqMTHu21UFeKaY1zng5NVqVqNmZZ/7P/oG0XBoucnrUibY5Hzy/YpRMdOEIDM1QdkKIY4UBxa1YXdmfnJftLyIEU5+OU10w6mzXGV7rfUnIrzUaY0KYN6S5TQ/rUM3wwUsZSJdD/eDc94xrwurtdBakYDGkwMRRV8gykx6jsFtPNWZg2D6u8usMuDwdeeuiFrdtL0pe6axD1PNtTAaerkkVu4QcxKXJ8V7dfH38uvBOfG3Tqwlvt+QLICKpdslmKnVNZTA6LFkNaugKJulWrh+j6UBCDJkvSepmbdHtHzxiVM7BxYyfkADRa8k9NLkv+BMrN4492zrvymm/hrjmP5RCJSk4FIHKya9zomMkqh+fyaOK9Fli6yJdw4gR3R1OaoTvkMcBppscSRq7WS6LoJysK/h+ZOO8K+Q3INF5qDOrpypi44EyJZGvzVSUVHBrbnnckA9J6LMg5lkENZJISo+YXHn1X+usuLpsUQa0Ji3otfYkX/Ohp4RqtHlESzH8Ae6a9jghbMHLW7nOE3eiE15txif9f603ljZWSKGHGDRLjKrQTU=
